import 'package:example/gen/fonts.gen.dart';
import 'package:flutter_bamboo_ui_kit/core.dart';

class ThemeConfig {
  final TTheme customLightTheme = TTheme(
    primary: HexColor(primary500),
    primaryForeground: HexColor(primary050),
    primaryPressed: HexColor(primary600),
    secondary: HexColor(secondary500),
    secondaryForeground: HexColor(secondary050),
    secondaryPressed: HexColor(secondary600),
    accent: HexColor(gray100),
    accentForeground: HexColor(gray950),
    destructive: HexColor(red500),
    destructiveForeground: HexColor(red050),
    destructivePressed: HexColor(red600),
    warning: HexColor(yellow500),
    warningForeground: HexColor(yellow050),
    warningPressed: HexColor(yellow600),
    success: HexColor(green500),
    successForeground: HexColor(green050),
    successPressed: HexColor(green600),
    info: HexColor(blue500),
    infoForeground: HexColor(blue050),
    ring: HexColor(gray500),
    active: HexColor(gray200),
    background: HexColor(baseWhite),
    foreground: HexColor(gray950),
    muted: HexColor(gray100),
    mutedForeground: HexColor(gray500),
    card: HexColor(baseWhite),
    cardForeground: HexColor(gray950),
    popover: HexColor(baseWhite),
    popoverForeground: HexColor(gray950),
    border: HexColor(gray200),
    input: HexColor(baseWhite),
    fontFamily: FontFamily.monserrat,
  );

  final TTheme customDarkTheme = TTheme(
    primary: HexColor(primary500),
    primaryForeground: HexColor(primary900),
    primaryPressed: HexColor(primary600),
    secondary: HexColor(secondary500),
    secondaryForeground: HexColor(secondary900),
    secondaryPressed: HexColor(secondary600),
    accent: HexColor(gray800),
    accentForeground: HexColor(gray050),
    destructive: HexColor(red500),
    destructiveForeground: HexColor(red900),
    destructivePressed: HexColor(red600),
    warning: HexColor(yellow500),
    warningForeground:HexColor(yellow900),
    warningPressed: HexColor(yellow600),
    success: HexColor(green500),
    successForeground: HexColor(primary900),
    successPressed: HexColor(green600),
    info: HexColor(blue500),
    infoForeground: HexColor(blue900),
    ring: HexColor(gray400),
    active: HexColor(gray500),
    background: HexColor(baseBlack),
    foreground: HexColor(gray050),
    muted: HexColor(gray950),
    mutedForeground: HexColor(gray400),
    card: HexColor(gray950),
    cardForeground: HexColor(red050),
    popover: HexColor(gray950),
    popoverForeground: HexColor(gray050),
    border: HexColor(gray700),
    input: HexColor(gray950),
    fontFamily: FontFamily.monserrat,
  );
}